### ISSUE TITLE
Fix before trying to organize your imports never goes away

### ISSUE THREAD

**Issue by razvbir** [scalameta/metals-zed#14]
![image](https://github.com/user-attachments/assets/737931ce-e748-4fc8-8f38-d448112d07a5)

I don't actually have any imports in that file. Is there a way to make this warning disappear after awhile?

**Comment by wjoel** [comment]
Zed calls codeActions all the time to be able to show them in the UI. Metals tells the client to show that message quite manually if OrganizeImports isn't available because the file has errors, so that's what Zed does: it just shows the message as it was instructed.

I think Metals should be using `disabled` in the response instead (which may not have existed in the LSP protocol back when OrganizeImports was first implemented), as in https://github.com/scalameta/metals/pull/6595
